// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eowxfgjdrduwkpjnpapa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVvd3hmZ2pkcmR1d2twam5wYXBhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUxOTk1MDAsImV4cCI6MjA3MDc3NTUwMH0.Ddkxr3vA9iEPZCnt3Ugh0XPJ__ROD5CX5ZbrmLrH_Ec";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});